---
# Let's Encrypt ClusterIssuers for cert-manager
# These create certificate issuers for the entire cluster
#
# Prerequisites:
#   1. cert-manager must be installed (see 00-cert-manager.yaml)
#   2. Update email address below with your actual email
#
# Usage:
#   kubectl apply -f 01-letsencrypt-issuer.yaml

# Let's Encrypt STAGING issuer (for testing)
# Use this first to test your setup without hitting rate limits
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # ⚠️ CHANGE THIS: Your email for Let's Encrypt notifications
    email: your-email@example.com

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-key

    # HTTP-01 challenge solver (works with Traefik ingress)
    solvers:
    - http01:
        ingress:
          class: traefik

---
# Let's Encrypt PRODUCTION issuer (for real certificates)
# Use this after testing with staging issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory

    # ⚠️ CHANGE THIS: Your email for Let's Encrypt notifications
    email: your-email@example.com

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-key

    # HTTP-01 challenge solver (works with Traefik ingress)
    solvers:
    - http01:
        ingress:
          class: traefik

